name: build docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t docker-image .

    - name: Run Cargo Doc
      run: |
        docker run --rm -v $(pwd)/temp_doc:/temp_doc --entrypoint /bin/sh docker-image -c "mkdir -p /temp_doc && cargo doc --no-deps --target-dir /temp_doc"
        cp -r temp_doc/$(ls temp_doc)/doc target/doc
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: cargo-doc
        path: target/doc
