name: build docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t docker-image .

    - name: Run Cargo Doc
      run: |
        docker run --rm -v $(pwd)/docs:/out --entrypoint /bin/sh docker-image -c "cargo doc --no-deps && cp -r /scratch/openshmem-rs/target/doc/openshmem_rs /out "
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: cargo-doc
        path: docs/openshmem_rs
