name: build docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t docker-image .

    - name: Run Cargo Doc
      run: |
        docker run --rm -v $(pwd)/docs:/out --entrypoint /bin/sh docker-image -c "cargo doc --no-deps && cp -r /scratch/openshmem-rs/target/doc/openshmem_rs /out "
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: docs/openshmem_rs
        overwrite: true
  deploy:
    environment:
      name: cargo-doc
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: build-and-doc
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
